// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6GkYKkplruOaK40O0jCksybxkGVL9ZTU',
    appId: '1:802755879997:web:b19a3ae66cf4d3eca27654',
    messagingSenderId: '802755879997',
    projectId: 'ejpride-605e5',
    authDomain: 'ejpride-605e5.firebaseapp.com',
    databaseURL: 'https://ejpride-605e5-default-rtdb.firebaseio.com',
    storageBucket: 'ejpride-605e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1FgU6nmJFutB4e7ldoxHFJcrbD8A3AeE',
    appId: '1:802755879997:android:0fa05323e360824ea27654',
    messagingSenderId: '802755879997',
    projectId: 'ejpride-605e5',
    databaseURL: 'https://ejpride-605e5-default-rtdb.firebaseio.com',
    storageBucket: 'ejpride-605e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeKQL_4I2p_VESfOV2wiivm0LC8oefbDw',
    appId: '1:802755879997:ios:1ee08ce969453ebda27654',
    messagingSenderId: '802755879997',
    projectId: 'ejpride-605e5',
    databaseURL: 'https://ejpride-605e5-default-rtdb.firebaseio.com',
    storageBucket: 'ejpride-605e5.firebasestorage.app',
    iosBundleId: 'com.example.ejpRideVersion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeKQL_4I2p_VESfOV2wiivm0LC8oefbDw',
    appId: '1:802755879997:ios:1ee08ce969453ebda27654',
    messagingSenderId: '802755879997',
    projectId: 'ejpride-605e5',
    databaseURL: 'https://ejpride-605e5-default-rtdb.firebaseio.com',
    storageBucket: 'ejpride-605e5.firebasestorage.app',
    iosBundleId: 'com.example.ejpRideVersion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6GkYKkplruOaK40O0jCksybxkGVL9ZTU',
    appId: '1:802755879997:web:4615b555b6b9b3f9a27654',
    messagingSenderId: '802755879997',
    projectId: 'ejpride-605e5',
    authDomain: 'ejpride-605e5.firebaseapp.com',
    databaseURL: 'https://ejpride-605e5-default-rtdb.firebaseio.com',
    storageBucket: 'ejpride-605e5.firebasestorage.app',
  );
}
