// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq3XcFG0gj6DGjrhcE2yzt480caRb6d_8',
    appId: '1:356608064184:web:01817cd74ec770ea7c924d',
    messagingSenderId: '356608064184',
    projectId: 'ejpride-54173',
    authDomain: 'ejpride-54173.firebaseapp.com',
    storageBucket: 'ejpride-54173.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzZw56-ewdHJXETtpW-BG-b7QGmZKd0wc',
    appId: '1:356608064184:android:01e8531392f7cbe97c924d',
    messagingSenderId: '356608064184',
    projectId: 'ejpride-54173',
    storageBucket: 'ejpride-54173.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqyKueUbM_8VN_L9_WRIDUA3yy2snQ_wQ',
    appId: '1:356608064184:ios:0138d7311a99720b7c924d',
    messagingSenderId: '356608064184',
    projectId: 'ejpride-54173',
    storageBucket: 'ejpride-54173.firebasestorage.app',
    iosBundleId: 'com.example.ejpRideVersion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqyKueUbM_8VN_L9_WRIDUA3yy2snQ_wQ',
    appId: '1:356608064184:ios:0138d7311a99720b7c924d',
    messagingSenderId: '356608064184',
    projectId: 'ejpride-54173',
    storageBucket: 'ejpride-54173.firebasestorage.app',
    iosBundleId: 'com.example.ejpRideVersion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfTOnOQhcbrGEDp_p_2G6pWFwlYlxp-4Y',
    appId: '1:356608064184:web:1fe4ba54d468fa4a7c924d',
    messagingSenderId: '356608064184',
    projectId: 'ejpride-54173',
    authDomain: 'ejpride-54173.firebaseapp.com',
    storageBucket: 'ejpride-54173.firebasestorage.app',
  );

}